"use client";
import { FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type Student={id:string;full_name:string|null;email:string|null}; type Course={id:string;name:string;category:string|null};
type Enrollment={id:string;student_id:string;course_code:string;course_name:string;course_category:string|null;status:string;enrolled_at:string};

export function EnrollmentsManager({students,courses,enrollments}:{students:Student[];courses:Course[];enrollments:Enrollment[]}){
 const router=useRouter(); const [query,setQuery]=useState(""); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState<{type:"success"|"error";text:string}|null>(null);
 const names=useMemo(()=>new Map(students.map(s=>[s.id,s])),[students]); const filtered=useMemo(()=>enrollments.filter(row=>`${row.course_name} ${names.get(row.student_id)?.full_name??""} ${names.get(row.student_id)?.email??""} ${row.status}`.toLowerCase().includes(query.toLowerCase().trim())),[enrollments,names,query]);
 async function request(url:string,init:RequestInit){setBusy(true);setNotice(null);try{const response=await fetch(url,init);const result=await response.json();if(!response.ok)throw new Error(result.error||"The request could not be completed.");setNotice({type:"success",text:"Course assignments updated."});router.refresh();}catch(error){setNotice({type:"error",text:error instanceof Error?error.message:"The request could not be completed."});}finally{setBusy(false)}}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);await request("/api/admin/enrollments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({studentId:data.get("studentId"),courseId:data.get("courseId"),status:"active"})});}
 return <div className="admin-manager-grid"><form className="admin-panel admin-create-form" onSubmit={submit}><div className="admin-form-heading"><span>New assignment</span><h2>Assign a course</h2><p>Courses are drawn from the website&apos;s verified course catalogue.</p></div><label><span>Student</span><select name="studentId" required defaultValue=""><option value="" disabled>Select student</option>{students.map(s=><option key={s.id} value={s.id}>{s.full_name||s.email||"Unnamed student"}</option>)}</select></label><label><span>Course</span><select name="courseId" required defaultValue=""><option value="" disabled>Select course</option>{courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button className="button button-primary" disabled={busy}>{busy?"Saving…":"Assign course"}</button>{notice&&<p className={`admin-notice admin-notice-${notice.type}`} role={notice.type==="error"?"alert":"status"}>{notice.text}</p>}</form><section className="admin-panel"><div className="admin-panel-heading"><div><span>Current records</span><h2>Course assignments</h2></div><input aria-label="Search assignments" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search assignments"/></div><div className="admin-record-list">{filtered.map(row=>{const student=names.get(row.student_id);return <article key={row.id}><div><strong>{row.course_name}</strong><small>{student?.full_name||"Unknown student"} · {student?.email||"No email"}</small></div><select aria-label={`Status for ${row.course_name}`} value={row.status} disabled={busy} onChange={e=>request("/api/admin/enrollments",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:row.id,status:e.target.value})})}><option value="active">Active</option><option value="completed">Completed</option><option value="paused">Paused</option><option value="cancelled">Cancelled</option></select><button className="admin-delete" disabled={busy} onClick={()=>{if(confirm("Remove this course assignment?"))request(`/api/admin/enrollments?id=${encodeURIComponent(row.id)}`,{method:"DELETE"})}}>Remove</button></article>})}{!filtered.length&&<div className="admin-empty"><strong>No assignments found</strong><p>Assign a verified course using the form.</p></div>}</div></section></div>;
}
