"use client";

import { FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

export type AdminStudent = { id:string; full_name:string|null; email:string|null; phone:string|null; created_at:string; enrollment_count:number };
type VerifiedCourse = { id: string; name: string };

export function StudentsBrowser({ students, courses }: { students: AdminStudent[]; courses: VerifiedCourse[] }) {
  const router=useRouter();
  const [query,setQuery]=useState("");
  const [busy,setBusy]=useState<string|null>(null);
  const [notice,setNotice]=useState<{type:"success"|"error";message:string}|null>(null);
  const filtered=useMemo(()=>students.filter(student=>`${student.full_name ?? ""} ${student.email ?? ""} ${student.phone ?? ""}`.toLowerCase().includes(query.toLowerCase().trim())),[students,query]);
  async function assign(event:FormEvent<HTMLFormElement>,student:AdminStudent){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);setBusy(student.id);setNotice(null);try{const response=await fetch("/api/admin/enrollments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({studentId:student.id,courseId:data.get("courseId"),status:data.get("status")})});const result=await response.json();if(!response.ok)throw new Error(result.error||"The course could not be assigned.");setNotice({type:"success",message:`${student.full_name||"Student"} was registered in the selected course.`});form.reset();router.refresh();}catch(error){setNotice({type:"error",message:error instanceof Error?error.message:"The course could not be assigned."});}finally{setBusy(null)}}
  return <>{notice&&<p className={`admin-notice admin-notice-${notice.type}`} role={notice.type==="error"?"alert":"status"}>{notice.message}</p>}<div className="admin-toolbar"><label><span>Search students</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Name, email, or mobile" /></label><p>{filtered.length} of {students.length} students</p></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Student</th><th>Contact</th><th>Assignments</th><th>Joined</th><th>Course registration</th></tr></thead><tbody>{filtered.map(student=><tr key={student.id}><td data-label="Student"><strong>{student.full_name || "Name unavailable"}</strong><small>{student.email || "Email unavailable"}</small></td><td data-label="Contact">{student.phone || "Not provided"}</td><td data-label="Assignments"><span className="admin-status active">{student.enrollment_count}</span></td><td data-label="Joined">{new Intl.DateTimeFormat("en-IN",{dateStyle:"medium"}).format(new Date(student.created_at))}</td><td data-label="Course registration"><details className="student-course-assign"><summary>Assign Course</summary><form onSubmit={event=>assign(event,student)}><label><span>Verified course</span><select name="courseId" required defaultValue=""><option value="" disabled>Select course</option>{courses.map(course=><option value={course.id} key={course.id}>{course.name}</option>)}</select></label><label><span>Status</span><select name="status" defaultValue="active"><option value="active">Active</option><option value="completed">Completed</option><option value="paused">Paused</option><option value="cancelled">Cancelled</option></select></label><button className="button button-primary button-small" disabled={busy===student.id}>{busy===student.id?"Saving…":"Register Student"}</button></form></details></td></tr>)}</tbody></table>{!filtered.length&&<div className="admin-empty"><strong>No students found</strong><p>Try a different search term.</p></div>}</div></>;
}
