import Link from "next/link";
import { getAdmin } from "@/lib/admin";

export const dynamic = "force-dynamic";

export default async function AdminDashboard() {
  const admin = await getAdmin(); if (!admin) return null;
  const today = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kolkata" }).format(new Date());
  const [students,enrollments,materials,announcements,events,recentStudents,recentMaterials,recentAnnouncements,upcomingEvents] = await Promise.all([
    admin.supabase.from("profiles").select("id",{count:"exact",head:true}).eq("role","student"), admin.supabase.from("student_enrollments").select("id",{count:"exact",head:true}).eq("status","active"), admin.supabase.from("study_materials").select("id",{count:"exact",head:true}).eq("is_published",true), admin.supabase.from("announcements").select("id",{count:"exact",head:true}).eq("is_published",true), admin.supabase.from("events").select("id",{count:"exact",head:true}).eq("is_published",true).gte("event_date",today),
    admin.supabase.from("profiles").select("id,full_name,email,created_at").eq("role","student").order("created_at",{ascending:false}).limit(4), admin.supabase.from("study_materials").select("id,title,course,is_published,created_at").order("created_at",{ascending:false}).limit(4), admin.supabase.from("announcements").select("id,title,is_published,published_at,created_at").order("created_at",{ascending:false}).limit(4), admin.supabase.from("events").select("id,title,event_date,is_published").gte("event_date",today).order("event_date").limit(4)
  ]);
  const cards = [["Total Students",students.count],["Active Enrollments",enrollments.count],["Published Materials",materials.count],["Published Announcements",announcements.count],["Upcoming Events",events.count]];
  return <div className="admin-dashboard"><header className="admin-page-heading"><div><p className="eyebrow"><span/> Administration</p><h1>Dashboard</h1><p>Real-time overview of student portal content.</p></div></header><div className="admin-metrics">{cards.map(([label,count]) => <article key={String(label)}><span>{label}</span><strong>{count ?? 0}</strong></article>)}</div><section className="admin-quick"><h2>Quick actions</h2><div>{[["Manage Students","/admin/students"],["Assign Courses","/admin/enrollments"],["Study Materials","/admin/study-materials"],["Create Announcement","/admin/announcements"],["Manage Events","/admin/events"]].map(([label,href])=><Link href={href} key={href}>{label}<span>→</span></Link>)}</div></section><div className="admin-dashboard-grid"><DashboardList title="Latest students" href="/admin/students" rows={(recentStudents.data??[]).map(x=>[x.full_name,x.email])}/><DashboardList title="Recent materials" href="/admin/study-materials" rows={(recentMaterials.data??[]).map(x=>[x.title,`${x.course} · ${x.is_published?"Published":"Draft"}`])}/><DashboardList title="Recent announcements" href="/admin/announcements" rows={(recentAnnouncements.data??[]).map(x=>[x.title,x.is_published?"Published":"Draft"])}/><DashboardList title="Nearest events" href="/admin/events" rows={(upcomingEvents.data??[]).map(x=>[x.title,`${x.event_date} · ${x.is_published?"Published":"Draft"}`])}/></div></div>;
}

function DashboardList({title,href,rows}:{title:string;href:string;rows:string[][]}) { return <section className="admin-dashboard-list"><div><h2>{title}</h2><Link href={href}>View all</Link></div>{rows.length ? rows.map((row,index)=><article key={`${row[0]}-${index}`}><strong>{row[0]}</strong><small>{row[1]}</small></article>) : <p>No records available.</p>}</section>; }
